/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UiList {
        "dataTable": any[];
        "headers": Headers[];
    }
}
declare global {
    interface HTMLUiListElement extends Components.UiList, HTMLStencilElement {
    }
    var HTMLUiListElement: {
        prototype: HTMLUiListElement;
        new (): HTMLUiListElement;
    };
    interface HTMLElementTagNameMap {
        "ui-list": HTMLUiListElement;
    }
}
declare namespace LocalJSX {
    interface UiList {
        "dataTable"?: any[];
        "headers"?: Headers[];
    }
    interface IntrinsicElements {
        "ui-list": UiList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-list": LocalJSX.UiList & JSXBase.HTMLAttributes<HTMLUiListElement>;
        }
    }
}
